### ISSUE TITLE
Likert Question require answer

### ISSUE THREAD

**Issue by ajwecker** [Craig-Creeger/react-likert-scale#24]
Great package!
Within a form is there a way to make a Likert Question required?

**Comment by Craig-Creeger** [comment]
Sure, you can use [Javascript client-side form validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#validating_forms_using_javascript) to read the value of the Likert scale and cancel the form submit if the value is missing.

I'm confident you can make it work with the Likert package as-is, but it may take some clever programming. I'll try to get an example put together, but honestly I'm not sure how quickly I can get that done.
