### ISSUE TITLE
Clear Likert Scale

### ISSUE THREAD

**Issue by isabelSoares** [Craig-Creeger/react-likert-scale#33]
Useful package!
How can I clear the Likert Scale input after the user submits the form?

**Comment by ccreeger** [comment]
You could do something similar to this:

```
import React, { useRef, useState } from 'react';
import Likert from './likert.js';

const likertOptions = {
  question:
    'What is your opinion of the President of the United State’s performance?',
  responses: [
    { value: 1, text: 'Abysmal' },
    { value: 2, text: 'Poor' },
    { value: 3, text: 'Average' },
    { value: 4, text: 'Good' },
    { value: 5, text: 'Excellent' },
  ],
};

export default function DemoInteraction() {
  const [render, forceRender] = useState(0);

  const reset = () => {
    forceRender(Date.now());
  };

  return (
    <>
      <Likert
        {...likertOptions}
        className='withBorder'
        key={render}
      />
      <p>
        <button onClick={reset}>Reset</button>
      </p>
    </>
  );
}
```

What it is doing is forcing the Likert scale to re-render with the original `responses`. You might be aware that React will re-render a component when any of the props change — that's what this does. It is changing the value of `key` to make the component re-render.

In your case, call `reset()` after the `<form>` has been submitted. Good luck!

**Comment by isabelSoares** [comment]
This solved my issue! Thank you very much.
